# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e16fdfea42083cf6534983750919e62ba9f41db356e0136717ed4e35f5acfb5e0e518e4bc469676d62f5469c2359477ebdce45a093411e03ce8aa1838311ec1e

test:
  secret_key_base: 4b11e70a7774e2e18a86621cdfe55adace09693280a0c0f3a403ef164a35879662aca3dc4f3dd6f635728778d46c91bb8b0a09f01b6780c0b1c3d7b0d47a3236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
